blank_issues_enabled: false
contact_links:
  - name: ❗️ All other issues
    url: https://github.com/PrivateAIM/node-message-broker/discussions
    about: |
      Please use GitHub Discussions for other issues and asking questions.
